server:
  port: 8081
#  servlet:
#    context-path: /auth

spring:
  security:
    user:
      password: pass
      name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

#security:
#  oauth2:
#    client:
#      client-id: first-client
#      client-secret: noonewilleverguess
#security:
#  oauth2:
#    client:
#      client-id: pattern-pedia-client
#      client-secret: iamaghost
#      authorized-grant-types: authorization_code,refresh_token,password
#      security.oauth2.client.scope: openid

#security:
#  jwt:
#    key-store: classpath:mykeystore.jks
#    key-store-password: pattern
#    key-pair-alias: pattern
#    key-pair-password: pattern

