server:
  port: 8081
#  servlet:
#    context-path: /auth

spring:
  security:
    user:
      password: pass
      name: user
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

#security:
#  oauth2:
#    client:
#      client-id: pattern-pedia-private
#      client-secret: pattern-pedia-secret
#    resource:
#      jwt:
#        key-value: pattern-pedia
#  jwt:
#    key-store: classpath:pattern-pedia-jwt.jks
#    key-store-password: pattern-pedia-store-pass
#    key-pair-alias: pattern-pediaoauth-jwt
#    key-pair-password: pattern-pedia-key-pass
#    authorizedGrantTypes: authorization_code, refresh_token
#    accessTokenValidititySeconds: 43200 # 12 hours
#    refreshTokenValiditySeconds: 2592000 # 30 days

#security:
#  oauth2:
#    resource:
#      filter-order: 3


#security:
#  oauth2:
#    client:
#      client-id: pattern-pedia-client
#      client-secret: iamaghost
#      authorized-grant-types: authorization_code,refresh_token,password
#      security.oauth2.client.scope: openid

#security:
#  jwt:
#    key-store: classpath:mykeystore.jks
#    key-store-password: pattern
#    key-pair-alias: pattern
#    key-pair-password: pattern

